language: java
dist: trusty

env:
  global:
  - secure: "vjOgUSG5EfA+PL+8jwWXV0AO/u6AZJc/DhOceDN47xUPfQyj5Prbmx8LXvw48AOYptHGtqIWG4BNJNPhZBi6LJY2ElAikbmI/y/mZ4ec+uiK0wewBxPw0nkzm5ZcjMaI1aotVyViSdwbRieI8qY/vubCWpH0NbX7ZvemCEqfUdWpMEbMlaNQgMqBhHJ5JJ5MmFGmmmxOqmTcGrSMhND9XXVPmlJbGJtsiyYvOvyAyxzdqply2bNSBC14Yvxjul1evmPL32orxk1B1a/0DLVnqHisxMGevtDiTxlu+7HurBCNzMvPU0QJe7ATaCUvZsyCGmxAMG5FmMbBiPM815zA5H7wJdrP0jlaFb4vvsQPU36KbmJONRD3OAWuCXgbAsGKdm0C8RJijorOTwJdBa7qDwldg17cty9fa1qetQFwqlZ/mZjSuQ/yUM+N6RhxNgSY53mTGg7yd8pGhC8sWThbBaZeRrY7x6GTQWZx9WQrQzPbxkJ8ysae/OxfKFntZlpypmy9Hl262u8xqq15/g7h9HsjeSH4KvTkil0jCpsvQ+PhyXAFaHvvE/NdehRwa10jQOxu7Sd/zGlLYljw3Noc7rAWDZobTsiZWSZNU+wiS1V9TCt/56FvwDScD4Ef02tT0c59c5VRIEj5oXQaCyaVevCnJxWie0rftOmoO2Yeauo="
  - secure: "Q5Hpe8LVTlgLS+/BNavnCAuGIJg5PMpuVVdMRxH9RO86kWsfvUYTaeuZrYWoKN1tQHAKjYHo/Jd9bua62AahtH3S4U3Iwv2UMXIr4JsZH58ZnG7x7dTEc3Kuk4gqm40w9i76515K3WyXgcOF47mVb2DiZUW7nzmxlOCOHc94DwOxIiZKKg8AjtxoCcaCHQnU+FfnWBfetFSONBULFBFCYfYQBhbSNeWNPrW7LRLMTLsjQzpN3snETg4FRGWbuEiOcaBjfJU6LypXy9j3E198Cj4i8pTiZm5ogYDSHSELqncRLDA+Pvk2fqxv+heKb+CkevM8RnSCbNL9I6d6bbOpKQoSpp/EzjNwS5GNpPwFOSl5QRPfp9wZhpVw4iP7y+5mKSmehBp898//A0n312sh0osJtYU+fPMWBxVm84+ZqlaRmRriuQjdx5SZlg9eptJkQXh3uddgAFLjZ2UDA2nKmSI2iVFKV6vFAKZUOva3NhHwaYzNwtdWj6tgjZ5qm1y263bYW2WXP7jAYjsV4fD2OqW1YLptD3bH+PmrQORBfELAsVm4co1L4/KJkc8ZgnXSg4n58uyD6buq5ezTn9p0w/kPCosSj24Kfrrw5p5ZlvZScCmUctYrtyyrkrjhxUcv/Gtim9LXa+WkOElBqTe+VHLU4dCV16uBviO/5P+trAE="
  - secure: "suPSEi306LXdIiGVrlxlgGojWH3tSkVXl2kqhJ2GQmivMdqvwqT7irxDWcohUgaIOeb2dC+HlD6r5i+oN7t/wqzvLXioXDjvuXOVjHWAHZQwwyjj1bLLH7HFFYuHLJeovFeeHRAYDIxPmWV6z5upTSr3NfnN9oJM3z2u1WNQHJMFDR1SeSVxpaI71/oF5qRl1w6g7mdRnTqSfm1HPYMXuCKo8K8tm9yEtETKBC4GTJfp9t1t2nmkyirZpuj2o6erBkphD24KxLmfitPb1Skwjid5X3way+C5gG6hvkL5TnUgSnjDBj2UmwJ4auVXgIZLbMgZNkwH261flwEvFWDRPunHNGAMENys4Ui+gbdMDT9Lb8yUU6h1GsGyj9ICfG54RlhsnF/sqOsdaZbS1AslVpdgHJvjd8tKV93Fdy0GlDcDUMUt2oSqXQsmtLYVTCQszNof0wxr0soYOx03nc8mj0T+wyYSWkIiKbmw1qaXmC48IcVvW+velJ4mFSKPrt/oEKHnMeVUFQyxURUjTHrN8MMetpj11jwl+KNyQBinjoOlu+F4WHDXfBBPFxDzhFgD81hf93JOczCJiaa0fLAuVNyNIGjnIS0e+UUJ+hkT1QOLa685LEHREn2fGzdOFgoA1LJX/GaJcbdv+lEIcLpVOaMEKvvcAz9xFOqwiuN3N90="

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_a16917e1e2f2_key -iv $encrypted_a16917e1e2f2_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
