language: java
dist: trusty

env:
  global:
  - secure: "jiGWtLFUFcWkqrd1cvU7hPn0oQH9FZRhcJxST5qEhDbzoayk5I1TP6KdxEtSza9IcKbE+SI1DxQ4rstYKapOIwvjj6kVZqeFsVVrXd1hvga+rRDNVCWOQ68S2Ne43DBNiFRhqNVBGIyURtHKs+A1kutVokNTN6/sn7YsEQD4YoQjktkNYqVaJ7JmAgvyZtgx5YpnkiFDPWKPSFFJCM7uVzNze0OO2U1IZ1ixNDP2kUYGuOoczgT8ciHnOJsyuzi0L3QAQtSYu2LYvBklc4Nd7ZUa7OAquu6w53aZWNOfXn0FZSQ2T9S0loeDi5jaHVNvyV9DKpFEE+ZjgB3itwQaXctKsF+bNTqG5wgaWzWS+WlfTwcnuobilYvb4iu+LbH6b7JWuNuIR4+Co92yhE1/m0+lzw/zfYJ4ld4HbXII18is4NXgBXXxhmnCK/W1spiSivYHMXG8hYNdo167sleuR+6H+/qIAJosIXlqCQtsXjhQUien3q0TFX0OMBcgeI/wxrFW9f7dKRSyQPeeAvg01YtBfreXsZApf4TyOQTDALtrNN/K3ZEglE/0CDshe2TwWZaL+LRxaKqBrkY6v+neo7mAzieYEZYoZNhmL6JjJdWXC+7uFhqI48IXnj8D+uH+ISPBEuOWAc0MGwWs85DxwEfENAuN8TuTaruN9+EbDe0="
  - secure: "C13FkF0T8aVpqktVpVZ3rOuv5ZPC8+SeDdDnOZMyaf4hK3ieAx/TBdQc5D7cvvue5HjDJPjeDuFmK+M5r8t+MaNnEAVyEVsdjoB9lcReewElnsCjg1X6s/TFe20jk8btT3Zs3JVW8UCaOjRIL9ZbF0kuod52fMWGvpiitrZG86BqxSUTIROdghjKf1wWXK2QYA6B/4ep8mkmeYqKfVTjv4B3F12P+rAIO78DL480twdDywWutAjC3YqUdrpWaVmeENSzxWuA4Cnjm4z0R+nLjheQ+xHSqhY+fmykZRq4qgKF249pdc8J2KmUTr7g5cHN9NT7onRtqc+J+96rswv8oPi2UF5eRwzSwe14TltI9PwfxbLYNRZiZKn2dWuvwyRguysiNaDq/9lgCH5YgDrijMuRJpPm7DxMqKBi5aFxYvW9sr4t3kBSEvl7Vb/sldWnOW26Xk00QeqND4jty2ejBwhKHO7BsfYYddgikiPTL6LtlsIfM2K0DYvKuK0TaxhaW2wkJhDBywKwumwCnYgCgqc7YnQSuNMe2w9mrY8vIaGtkRDOyPGJ/5SWc6hNExnXZ4QNqwexybFUD/SpZN2aKskpyES9urJrjzIdCS8X95FH4/684+nscTxrsqW4OoB49yHlPTIkIbg0TLDI0l+z9qjlE6uGMS6vcRVOkqMjE2w="
  - secure: "hAVNQzX5NX1H9mr8MSnwuivJkAUjXgph0gaWsKzDNHy+xm3GUPYSua0DrdKlCVxM4NfLml0R+Rl9zl9b4ykZu2Sy3i1JanoxhVS7359mlstpG7ml860ACpG7g1ScL7DVhWrCwBSzcOiENY9KGrAfOjwcnqLIbRKsHTbsASDRiKXqyrxH057xhAjWQKiN8CemCpvuZ+jcn9MA9B7mk1kQRN1zrhscrNnnNG/t6865vK5RUKsrciAumvBgmB2w8hZfYcXthBMQBz6FoNPgwpoOFyX/KVblRrccRIE0zUAzq7Q8bpa0TtPQOCHWxgxneA75QScQwCPic3QU9434vFw7+hl5sjfgkKWhyYQy/ztANknHUBI2pQZk3q1y2TEy1G/BSW8dE2f0NfYSLD7WIfzDoHiP9zEtK6FtpXncGA8NTfxToVIVwQQXclS9HKRu/sRP5zc2sQ3FpZCp+kpEHK9vsPMq5mSX3kXKTg3F7iAbWG1ni2pO5VWi2D34IH6KB4ktVAQ2tDDaxllIpJNomijWkFkjaj/5Io0HRZQ8dXb+hgaahwMu7s4knGl3dLqaBuIVm7aD26WIj2at1/d9OIQVWqsAN9VhCDtkbOTWV0EXcespvLbhNvd+hXwPdliasqp4ZDY+bwp1+i05sCEaYfpol1uNqSdVwGfkijD/meZ1sXc="

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_53a2d61b1267_key -iv $encrypted_53a2d61b1267_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
